/**
 * Lead readiness model.
 *
 * Stage A (current): transparent weighted coefficients, hand-set from domain
 * knowledge so the ranking is useful before any conversion history exists.
 *
 * Stage B: `scripts/train_lead_scorer.py` trains a logistic model on real
 * won/lost outcomes and rewrites the COEFFICIENTS block below in place. The
 * interface — `scoreLead` in, 0-100 + reasons out — never changes, so nothing
 * else in the app has to be touched when the real model lands.
 */

export type ModelCoefficients = {
  version: string;
  trained_on: number;
  intercept: number;
  bill_range: Record<string, number>;
  solution_interest: Record<string, number>;
  property_type: Record<string, number>;
  source_channel: Record<string, number>;
  entry_mode: Record<string, number>;
  has_booked_slot: number;
  wrote_notes: number;
  age_days_per_week_decay: number;
};

// ---- COEFFICIENTS (regenerated by the training script) ----
export const COEFFICIENTS: ModelCoefficients = {
  version: "stage-a-heuristic",
  trained_on: 0,
  intercept: -0.9,
  bill_range: {
    "Under $150": -0.9,
    "$150 – $300": -0.1,
    "$300 – $500": 0.7,
    "$500 – $800": 1.2,
    "Over $800": 1.6,
  },
  solution_interest: {
    "Stationary Outbuilding Power Vault": 0.35,
    "Mobile Silent Generator": 0.15,
    "Turnkey Combo": 0.8,
  },
  property_type: {
    "Single Family": 0.2,
    "Multi-Family": 0.35,
    "Commercial Facility": 0.7,
    "Service Van / Fleet": 0.05,
  },
  source_channel: {},
  entry_mode: {
    manual: 0.3,
    web_form: 0,
  },
  has_booked_slot: 0.9,
  wrote_notes: 0.4,
  age_days_per_week_decay: -0.18,
};
// ---- END COEFFICIENTS ----


export type ScorableLead = {
  monthly_bill_range: string | null;
  solution_interest: string | null;
  property_type: string | null;
  slot_id: string | null;
  notes: string | null;
  created_at: string;
  source_channel?: string | null;
  entry_mode?: string | null;
};


export type LeadScore = {
  score: number;
  reasons: { label: string; weight: number }[];
};

const sigmoid = (x: number) => 1 / (1 + Math.exp(-x));

export function scoreLead(lead: ScorableLead, now: Date = new Date()): LeadScore {
  const c = COEFFICIENTS;
  const reasons: { label: string; weight: number }[] = [];

  const push = (label: string, weight: number | undefined) => {
    if (weight === undefined || weight === 0) return;
    reasons.push({ label, weight });
  };

  const bill = lead.monthly_bill_range ?? "";
  push(`Bill band: ${bill || "unknown"}`, c.bill_range[bill]);

  const solution = lead.solution_interest ?? "";
  push(`Interest: ${solution || "unspecified"}`, c.solution_interest[solution]);

  const property = lead.property_type ?? "";
  push(`Site: ${property || "unspecified"}`, c.property_type[property]);

  const channel = lead.source_channel ?? "";
  if (channel) push(`Came via: ${channel}`, c.source_channel[channel]);

  const mode = lead.entry_mode ?? "";
  if (mode) push(mode === "manual" ? "Logged from a live conversation" : "Web form", c.entry_mode[mode]);

  if (lead.slot_id) push("Booked an assessment slot", c.has_booked_slot);

  if (lead.notes && lead.notes.trim().length > 12) push("Wrote detailed notes", c.wrote_notes);

  const ageDays = Math.max(0, (now.getTime() - new Date(lead.created_at).getTime()) / 86_400_000);
  const decay = (ageDays / 7) * c.age_days_per_week_decay;
  if (Math.abs(decay) > 0.01) push(`Ageing (${Math.round(ageDays)}d in pipeline)`, decay);

  const logit = c.intercept + reasons.reduce((sum, r) => sum + r.weight, 0);
  const score = Math.round(sigmoid(logit) * 100);

  reasons.sort((a, b) => Math.abs(b.weight) - Math.abs(a.weight));
  return { score, reasons };
}

export function scoreBand(score: number): "hot" | "warm" | "cool" {
  if (score >= 65) return "hot";
  if (score >= 35) return "warm";
  return "cool";
}
