#!/usr/bin/env bash
# One command to go from a bare Omen/WSL shell to the app running in dev mode.
#
#   bash docs/omen-setup/start.sh
#
# It will:
#   1. Run the bootstrap installer (skipped if the toolchain is already present).
#   2. Make sure a .env file exists with the backend variables the app needs.
#   3. Start the dev server on http://localhost:8080
#
# Flags:
#   --skip-bootstrap   don't re-run the installer
#   --reconfigure      re-enter the backend environment variables
#   --port <n>         serve on a different port (default 8080)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
cd "$REPO_ROOT"

PORT=8080
SKIP_BOOTSTRAP=0
RECONFIGURE=0

while [ $# -gt 0 ]; do
  case "$1" in
    --skip-bootstrap) SKIP_BOOTSTRAP=1; shift ;;
    --reconfigure)    RECONFIGURE=1; shift ;;
    --port)           PORT="${2:?--port needs a value}"; shift 2 ;;
    -h|--help)        sed -n '2,15p' "${BASH_SOURCE[0]}"; exit 0 ;;
    *) echo "Unknown option: $1" >&2; exit 1 ;;
  esac
done

log()  { printf '\n\033[1;33m==> %s\033[0m\n' "$1"; }
have() { command -v "$1" >/dev/null 2>&1; }

export PATH="$HOME/.bun/bin:$HOME/.local/bin:$PATH"

# ---------------------------------------------------------------- bootstrap --
if [ "$SKIP_BOOTSTRAP" -eq 0 ]; then
  if have bun && have ffmpeg && have git && [ -d node_modules ]; then
    log "Toolchain already installed — skipping bootstrap (use --skip-bootstrap to force skip)"
  else
    log "Running bootstrap installer"
    bash "$SCRIPT_DIR/bootstrap-omen.sh"
    export PATH="$HOME/.bun/bin:$HOME/.local/bin:$PATH"
  fi
fi

if ! have bun; then
  echo "bun is still not on PATH. Close and reopen the terminal, then re-run this script." >&2
  exit 1
fi

# ------------------------------------------------------------------- .env ----
ENV_FILE="$REPO_ROOT/.env"

needs_env() {
  [ "$RECONFIGURE" -eq 1 ] && return 0
  [ -f "$ENV_FILE" ] || return 0
  for key in VITE_SUPABASE_URL VITE_SUPABASE_PUBLISHABLE_KEY VITE_SUPABASE_PROJECT_ID; do
    grep -q "^${key}=." "$ENV_FILE" || return 0
  done
  return 1
}

if needs_env; then
  log "Backend environment variables needed"
  cat <<'EOF'
Copy these three values from your Lovable project (they are the publishable /
client-side values, safe to keep on your machine):

  VITE_SUPABASE_URL
  VITE_SUPABASE_PUBLISHABLE_KEY
  VITE_SUPABASE_PROJECT_ID

EOF
  read -r -p "VITE_SUPABASE_URL: " SB_URL
  read -r -p "VITE_SUPABASE_PUBLISHABLE_KEY: " SB_KEY
  read -r -p "VITE_SUPABASE_PROJECT_ID: " SB_ID

  if [ -z "$SB_URL" ] || [ -z "$SB_KEY" ] || [ -z "$SB_ID" ]; then
    echo "All three values are required. Re-run when you have them." >&2
    exit 1
  fi

  [ -f "$ENV_FILE" ] && cp "$ENV_FILE" "$ENV_FILE.bak"

  cat > "$ENV_FILE" <<EOF
# Generated by docs/omen-setup/start.sh — client-side backend config.
VITE_SUPABASE_URL=$SB_URL
VITE_SUPABASE_PUBLISHABLE_KEY=$SB_KEY
VITE_SUPABASE_PROJECT_ID=$SB_ID

# Server-side mirrors (same values, read by server functions).
SUPABASE_URL=$SB_URL
SUPABASE_PUBLISHABLE_KEY=$SB_KEY
SUPABASE_PROJECT_ID=$SB_ID
EOF
  chmod 600 "$ENV_FILE"
  log "Wrote $ENV_FILE"
else
  log "Using existing .env"
fi

# --------------------------------------------------------------- install -----
if [ ! -d node_modules ]; then
  log "Installing project dependencies"
  bun install
fi

# ------------------------------------------------------------------ run ------
log "Starting dev server on http://localhost:$PORT"
echo "Press Ctrl+C to stop."
exec bun run dev --port "$PORT" --host
