#!/usr/bin/env python3
"""
Earth Protection Society — lead readiness model trainer.

Runs locally on the workshop machine (HP Omen 45L). The dataset is small and
tabular, so this trains in seconds on CPU; no GPU required, and no customer
data leaves the machine.

Usage
-----
    python scripts/train_lead_scorer.py eps-lead-training.csv

Input
-----
The CSV exported from the capacity console
(Operations -> Lead readiness queue -> "Export training data"), with columns:
    bill_range, solution_interest, property_type, booked_slot,
    has_notes, age_days, label        # label: 1 = won, 0 = lost

Output
------
    1. coefficients.json   — next to your CSV, for the record / inspection.
    2. src/lib/lead-model.ts is REWRITTEN in place with the new COEFFICIENTS
       block, so the app's scoring is updated the next time you run it. Just
       git add + commit + push, and the change reaches the published site.

Train once you have roughly 150 labelled outcomes. Below that the starter
model in the app is the more honest estimate (the script warns, not blocks).
"""

import json
import sys
from pathlib import Path

import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import cross_val_score

MIN_ROWS = 60
RECOMMENDED_ROWS = 150

CATEGORICALS = ["bill_range", "solution_interest", "property_type"]

# Markers that delimit the COEFFICIENTS block in src/lib/lead-model.ts.
START_MARKER = "// ---- COEFFICIENTS (regenerated by the training script) ----"
END_MARKER = "// ---- END COEFFICIENTS ----"


def find_repo_root(csv_path: Path) -> Path:
    """Walk up from the CSV until we find the src/lib/lead-model.ts file."""
    cur = csv_path.resolve()
    for _ in range(6):
        if (cur / "src" / "lib" / "lead-model.ts").exists():
            return cur
        if cur.parent == cur:
            break
        cur = cur.parent
    sys.exit(
        "Could not locate src/lib/lead-model.ts above this CSV. "
        "Run the script from inside the project folder (green-glide-groove)."
    )


def fmt_num(v: float) -> str:
    """Round-trip a float to 4 decimals as a readable TS number literal."""
    s = f"{v:.4f}".rstrip("0").rstrip(".")
    return s if s not in ("", "-") else "0"


def format_block(out: dict) -> str:
    """Render the COEFFICIENTS object as TypeScript source."""
    def group(d: dict, indent: str) -> str:
        items = [f'{indent}    {json.dumps(k)}: {fmt_num(v)},' for k, v in d.items()]
        return "\n".join(items)

    return (
        f"{START_MARKER}\n"
        f"export const COEFFICIENTS: ModelCoefficients = {{\n"
        f'  version: {json.dumps(out["version"])},\n'
        f'  trained_on: {out["trained_on"]},\n'
        f"  intercept: {fmt_num(out['intercept'])},\n"
        f"  bill_range: {{\n{group(out['bill_range'], '')}\n  }},\n"
        f"  solution_interest: {{\n{group(out['solution_interest'], '')}\n  }},\n"
        f"  property_type: {{\n{group(out['property_type'], '')}\n  }},\n"
        f"  has_booked_slot: {fmt_num(out['has_booked_slot'])},\n"
        f"  wrote_notes: {fmt_num(out['wrote_notes'])},\n"
        f"  age_days_per_week_decay: {fmt_num(out['age_days_per_week_decay'])},\n"
        f"}};\n"
        f"{END_MARKER}"
    )


def patch_lead_model(ts_path: Path, out: dict) -> None:
    """Replace the COEFFICIENTS block in lead-model.ts in place."""
    src = ts_path.read_text()
    start = src.find(START_MARKER)
    end = src.find(END_MARKER)
    if start == -1 or end == -1:
        sys.exit("Could not find the COEFFICIENTS markers in lead-model.ts — aborting without changes.")
    end += len(END_MARKER)
    new = src[:start] + format_block(out) + src[end:]
    ts_path.write_text(new)
    print(f"patched {ts_path}")


def main(csv_path: str) -> None:
    df = pd.read_csv(csv_path)
    df = df.dropna(subset=["label"])

    n = len(df)
    if n < MIN_ROWS:
        sys.exit(
            f"Only {n} labelled rows. Need at least {MIN_ROWS} to train anything "
            f"meaningful, {RECOMMENDED_ROWS} for a model worth shipping. "
            "Keep marking leads won/lost in the console."
        )
    if n < RECOMMENDED_ROWS:
        print(f"[warn] {n} rows — under the recommended {RECOMMENDED_ROWS}. Treat the output as provisional.")

    if df["label"].nunique() < 2:
        sys.exit("Every row has the same outcome. Need both won and lost examples.")

    # One-hot the categoricals, keep the numeric features as-is.
    x_cat = pd.get_dummies(df[CATEGORICALS], prefix=CATEGORICALS, prefix_sep="=")
    x_num = df[["booked_slot", "has_notes"]].astype(float)
    x_num["age_weeks"] = df["age_days"].astype(float) / 7.0
    x = pd.concat([x_cat, x_num], axis=1)
    y = df["label"].astype(int)

    model = LogisticRegression(max_iter=2000, C=1.0)
    model.fit(x, y)

    folds = min(5, int(y.value_counts().min()))
    if folds >= 2:
        auc = cross_val_score(model, x, y, cv=folds, scoring="roc_auc").mean()
    else:
        auc = roc_auc_score(y, model.predict_proba(x)[:, 1])
    print(f"cross-validated AUC: {auc:.3f}  (0.5 = coin flip, 0.7+ = useful)")

    weights = dict(zip(x.columns, model.coef_[0]))

    def group(prefix: str) -> dict:
        return {
            col.split("=", 1)[1]: round(float(w), 4)
            for col, w in weights.items()
            if col.startswith(prefix + "=")
        }

    out = {
        "version": f"trained-{pd.Timestamp.utcnow():%Y-%m-%d}-auc{auc:.2f}",
        "trained_on": n,
        "intercept": round(float(model.intercept_[0]), 4),
        "bill_range": group("bill_range"),
        "solution_interest": group("solution_interest"),
        "property_type": group("property_type"),
        "has_booked_slot": round(float(weights.get("booked_slot", 0.0)), 4),
        "wrote_notes": round(float(weights.get("has_notes", 0.0)), 4),
        "age_days_per_week_decay": round(float(weights.get("age_weeks", 0.0)), 4),
    }

    dest = Path(csv_path).with_name("coefficients.json")
    dest.write_text(json.dumps(out, indent=2))
    print(f"wrote {dest}")

    repo_root = find_repo_root(Path(csv_path))
    patch_lead_model(repo_root / "src" / "lib" / "lead-model.ts", out)
    print(
        "\nDone. The app's COEFFICIENTS are updated. Commit and push to ship it:\n"
        "    git add src/lib/lead-model.ts && git commit -m 'retrain lead scorer' && git push\n"
        "Then re-start the app (bash docs/omen-setup/start.sh)."
    )


if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit("usage: python scripts/train_lead_scorer.py <eps-lead-training.csv>")
    main(sys.argv[1])
