/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CreatorsRouteImport } from './routes/creators'
import { Route as EnergyRouteImport } from './routes/energy'
import { Route as MobilityRouteImport } from './routes/mobility'
import { Route as StoreRouteImport } from './routes/store'
import { Route as CHandleRouteImport } from './routes/c.$handle'
import { Route as ProducersSlugRouteImport } from './routes/producers.$slug'
import { Route as AuthenticatedCreatorDashboardRouteImport } from './routes/_authenticated/creator/dashboard'
import { Route as AuthenticatedOpsCapacityRouteImport } from './routes/_authenticated/ops/capacity'
import { Route as AuthenticatedOpsStoresRouteImport } from './routes/_authenticated/ops/stores'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorsRoute = CreatorsRouteImport.update({
  id: '/creators',
  path: '/creators',
  getParentRoute: () => rootRouteImport,
} as any)
const EnergyRoute = EnergyRouteImport.update({
  id: '/energy',
  path: '/energy',
  getParentRoute: () => rootRouteImport,
} as any)
const MobilityRoute = MobilityRouteImport.update({
  id: '/mobility',
  path: '/mobility',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const CHandleRoute = CHandleRouteImport.update({
  id: '/c/$handle',
  path: '/c/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const ProducersSlugRoute = ProducersSlugRouteImport.update({
  id: '/producers/$slug',
  path: '/producers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCreatorDashboardRoute =
  AuthenticatedCreatorDashboardRouteImport.update({
    id: '/creator/dashboard',
    path: '/creator/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpsCapacityRoute =
  AuthenticatedOpsCapacityRouteImport.update({
    id: '/ops/capacity',
    path: '/ops/capacity',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpsStoresRoute = AuthenticatedOpsStoresRouteImport.update({
  id: '/ops/stores',
  path: '/ops/stores',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/creators': typeof CreatorsRoute
  '/energy': typeof EnergyRoute
  '/mobility': typeof MobilityRoute
  '/store': typeof StoreRoute
  '/c/$handle': typeof CHandleRoute
  '/producers/$slug': typeof ProducersSlugRoute
  '/creator/dashboard': typeof AuthenticatedCreatorDashboardRoute
  '/ops/capacity': typeof AuthenticatedOpsCapacityRoute
  '/ops/stores': typeof AuthenticatedOpsStoresRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/creators': typeof CreatorsRoute
  '/energy': typeof EnergyRoute
  '/mobility': typeof MobilityRoute
  '/store': typeof StoreRoute
  '/c/$handle': typeof CHandleRoute
  '/producers/$slug': typeof ProducersSlugRoute
  '/creator/dashboard': typeof AuthenticatedCreatorDashboardRoute
  '/ops/capacity': typeof AuthenticatedOpsCapacityRoute
  '/ops/stores': typeof AuthenticatedOpsStoresRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/creators': typeof CreatorsRoute
  '/energy': typeof EnergyRoute
  '/mobility': typeof MobilityRoute
  '/store': typeof StoreRoute
  '/c/$handle': typeof CHandleRoute
  '/producers/$slug': typeof ProducersSlugRoute
  '/_authenticated/creator/dashboard': typeof AuthenticatedCreatorDashboardRoute
  '/_authenticated/ops/capacity': typeof AuthenticatedOpsCapacityRoute
  '/_authenticated/ops/stores': typeof AuthenticatedOpsStoresRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/community'
    | '/creators'
    | '/energy'
    | '/mobility'
    | '/store'
    | '/c/$handle'
    | '/producers/$slug'
    | '/creator/dashboard'
    | '/ops/capacity'
    | '/ops/stores'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/community'
    | '/creators'
    | '/energy'
    | '/mobility'
    | '/store'
    | '/c/$handle'
    | '/producers/$slug'
    | '/creator/dashboard'
    | '/ops/capacity'
    | '/ops/stores'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/community'
    | '/creators'
    | '/energy'
    | '/mobility'
    | '/store'
    | '/c/$handle'
    | '/producers/$slug'
    | '/_authenticated/creator/dashboard'
    | '/_authenticated/ops/capacity'
    | '/_authenticated/ops/stores'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CommunityRoute: typeof CommunityRoute
  CreatorsRoute: typeof CreatorsRoute
  EnergyRoute: typeof EnergyRoute
  MobilityRoute: typeof MobilityRoute
  StoreRoute: typeof StoreRoute
  CHandleRoute: typeof CHandleRoute
  ProducersSlugRoute: typeof ProducersSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creators': {
      id: '/creators'
      path: '/creators'
      fullPath: '/creators'
      preLoaderRoute: typeof CreatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/energy': {
      id: '/energy'
      path: '/energy'
      fullPath: '/energy'
      preLoaderRoute: typeof EnergyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobility': {
      id: '/mobility'
      path: '/mobility'
      fullPath: '/mobility'
      preLoaderRoute: typeof MobilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$handle': {
      id: '/c/$handle'
      path: '/c/$handle'
      fullPath: '/c/$handle'
      preLoaderRoute: typeof CHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producers/$slug': {
      id: '/producers/$slug'
      path: '/producers/$slug'
      fullPath: '/producers/$slug'
      preLoaderRoute: typeof ProducersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/creator/dashboard': {
      id: '/_authenticated/creator/dashboard'
      path: '/creator/dashboard'
      fullPath: '/creator/dashboard'
      preLoaderRoute: typeof AuthenticatedCreatorDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ops/capacity': {
      id: '/_authenticated/ops/capacity'
      path: '/ops/capacity'
      fullPath: '/ops/capacity'
      preLoaderRoute: typeof AuthenticatedOpsCapacityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ops/stores': {
      id: '/_authenticated/ops/stores'
      path: '/ops/stores'
      fullPath: '/ops/stores'
      preLoaderRoute: typeof AuthenticatedOpsStoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCreatorDashboardRoute: typeof AuthenticatedCreatorDashboardRoute
  AuthenticatedOpsCapacityRoute: typeof AuthenticatedOpsCapacityRoute
  AuthenticatedOpsStoresRoute: typeof AuthenticatedOpsStoresRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCreatorDashboardRoute: AuthenticatedCreatorDashboardRoute,
  AuthenticatedOpsCapacityRoute: AuthenticatedOpsCapacityRoute,
  AuthenticatedOpsStoresRoute: AuthenticatedOpsStoresRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CommunityRoute: CommunityRoute,
  CreatorsRoute: CreatorsRoute,
  EnergyRoute: EnergyRoute,
  MobilityRoute: MobilityRoute,
  StoreRoute: StoreRoute,
  CHandleRoute: CHandleRoute,
  ProducersSlugRoute: ProducersSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
